# docker-compose.yml

version: '3.8'

services:
  # --- Serviço do Backend (API) ---
  backend:
    image: orickjogando/recrutamentoia-backend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.backend
    # ⚠️  IMPORTANTE: Configure as variáveis de ambiente no Portainer!
    # Copie o conteúdo do arquivo PORTAINER_ENV_VARS.txt na seção 
    # "Environment variables" do stack no Portainer.
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Foco"
        - "traefik.http.routers.backend-router.rule=Host(`backend.recrutamentoia.com.br`)"
        - "traefik.http.routers.backend-router.entrypoints=websecure"
        - "traefik.http.routers.backend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.backend-service.loadbalancer.server.port=3001"

  # --- Serviço do Frontend (React App) ---
  frontend:
    image: orickjogando/recrutamentoia-frontend:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # NOTA: A sua plataforma ignora esta secção. A variável deve ser configurada na UI.
      args:
        VITE_API_BASE_URL: https://backend.recrutamentoia.com.br
    networks:
      - traefik_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=Foco"
        - "traefik.http.routers.frontend-router.rule=Host(`recrutamentoia.com.br`) || Host(`www.recrutamentoia.com.br`)"
        - "traefik.http.routers.frontend-router.entrypoints=websecure"
        - "traefik.http.routers.frontend-router.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend-service.loadbalancer.server.port=80"

networks:
  traefik_network:
    external: true
    name: Foco
